### ISSUE TITLE
Continuous deployment of mangrove.js to npm

### ISSUE THREAD

**Issue by espendk** [mangrovedao/mangrove-ts#158]
2022-01-24 Dev meeting decision: @akettal will look into this a bit more and make a more detailed proposal on how we can do CD in a way that fits with the development workflow we want.
----
This issue is a work-in-progress. We use it to gather information and ideas about how to implement continuous deployment of mangrove.js to npm.

# Motivation
We'd like to have continuous deployment of mangrove.js to npm for the following reasons:

- shorter lead time
- smaller risk of error
- reduced overhead for operations.

# Analysis
Creation of a new mangrove.js package involves the following steps that must be automated ([see the deployment checklist on Notion](https://www.notion.so/mangroveexchange/mangrove-js-deployment-checklist-bb509418aadd4181a320c6dd32da5aee)):

- Creation of release notes
    - Currently this is done by manually manipulating CHANGELOG.md
- Increment the version number
    - Currently this is done by manually creating a release branch and deciding whether the release is major, minor, or a patch and executing the corresponding `yarn publish_{major|minor|patch}`
- Publish to npm
    - Currently this happens automatically as part of the previous step
- Creating a release tag
    - Currently this is done manually using git
- Make a release on GitHub
    - Currently this is done manually on GitHub

# Tools
There are tools that can do most/all of the work:

## [semantic-release](https://github.com/semantic-release/semantic-release)

> semantic-release automates the whole package release workflow including: determining the next version number, generating the release notes, and publishing the package.

Here's a recent introduction on how it can be used: [Continuous Deployment for publishing NPM packages](https://medium.com/techmindtickle/continuous-deployment-for-publishing-packages-4e5ef327ea37) 

semantic-release relies on commit messages following the Conventional Commits standard. From this, semantic version numbers and release notes can be generated.

@akettal has experience with semantic-release and says it works smoothly.

[semantic-release-monorepo](https://github.com/pmowrer/semantic-release-monorepo) is an extension that should support our monorepo setup.
It filters the commit messages based on the files/packages the commit touches.

## [Release Please](https://github.com/googleapis/release-please)

> Release Please automates CHANGELOG generation, the creation of GitHub releases, and version bumps for your projects.
> 
> It does so by parsing your git history, looking for Conventional Commit messages, and creating release PRs.

Release Please does not automatically deploy but instead maintains a PR with information about a release. When this PR is merged, a release is created.

Release Please also relies on Conventional Commits. But version numbers are not inferred: They must be set by committing a special commit message: https://github.com/googleapis/release-please#how-do-i-change-the-version-number.

## [Lerna](https://github.com/lerna/lerna)
Lerna should be able to help with releasing packages from a monorepo.

We've previously looked at Lerna, see the notes on Notion:
- [Survey of monorepo tools](https://www.notion.so/mangroveexchange/Survey-of-monorepo-tools-b0e65b4361924756936a79e8078a4cef)
- [Notes on dependencies and monorepos (2021-09-17)](https://www.notion.so/mangroveexchange/Notes-on-dependencies-and-monorepos-2021-09-17-cbabae8e2fa345a88a51c57be87c12ae)

Lerna requires more investigation.

# Solution ideas and thoughts
## Commit messages control version numbers and release notes
It seems disciplined commit messages is an easy and common way to control automatic versioning and generation of release notes.

The most common format seems to be [Conventional Commits](https://www.conventionalcommits.org/).

If we go this route, we should set up a precommit hook that verifies the commit message.

## Fully automated VS semi-automated
Do we wish to go fully automated (using e.g. semantic-release) or do want to control when a release is created/deployed (using e.g. Release Please)?

2022-01-21 Espen: Fully automated seems to be ideal from a maintenance effort perspective. As it is also unclear why we would not want to deploy whenever `master` is updated, I would propose we go for full automation first. If this turns out to have negative side-effects, we can move to something less automated.

**Comment by peterMangrove** [comment]
This issue is still very relevant. Some more thoughts on the topic can be found [here](https://www.notion.so/mangroveexchange/Continuous-deployment-of-mangrove-js-62faf596d45e42dc93f3aaaeb19128a2)
