### ISSUE TITLE
OB Filler is ill configured

### ISSUE THREAD

**Issue by jkrivine** [mangrovedao/mangrove-ts#210]
**Describe the bug**
OB filler keeps posting Asks and no bids. It also creates a negative spread. Furthermore the liquidity it promises is very low (which creates ugly order books, with interesting liquidity too far away)

**Screenshots**

<img width="1988" alt="Screenshot 2022-02-21 at 17 28 50" src="https://user-images.githubusercontent.com/293262/154994491-7571715f-87ff-4ee1-9667-485b6f80ab65.png">

**Comment by espendk** [comment]
@adhusson is this still relevant?

**Comment by espendk** [comment]
Closing this as deprecated.
