### ISSUE TITLE
Add functions to enable`permit` and `marketOrderFor` in the API

### ISSUE THREAD

**Issue by jkrivine** [mangrovedao/mangrove-ts#239]
`permit` function need user to forge a secp256k1 signature. This is required if `marketOrderFor` and `snipeFor` functions are to be used by a delegate taker (such as a bot).
Support for an easy use of `permit` (and by extension `marketOrderFor` would be quite useful for bot makers.

**Comment by adhusson** [comment]
Being handled in #828

**Comment by peterMangrove** [comment]
This should be solved in the PR #828.
