### ISSUE TITLE
hard to catch failing offers

### ISSUE THREAD

**Issue by vd1** [mangrovedao/mangrove-ts#347]
Suppose I post an offer which fails based on a hard to predict time-dependent value -such as whether the hash of the latest block starts with an `f`. For a keeper bot to catch it it needs to dry-run it at a frequency which is roughly double that of the chain itself.

┆Issue is synchronized with this [Monday item](https://mangrovedao.monday.com/boards/3894180513/pulses/3901989845) by [Unito](https://www.unito.io)

**Comment by jkrivine** [comment]
I guess these offer succeed often enough so that keepers don't need to catch them urgently.

**Comment by peterMangrove** [comment]
@vd1 I'm not sure what the task is here. Can you describe it more?

**Comment by peterMangrove** [comment]
Hi @vd1, after talking a bit with @espendk, we have decided to close this issue. Not that we don't see your point, but since there is no real task here we are going to close it. When we have a better idea of how to handle a way to better clean offers, we can then create a new issue.

**Comment by vd1** [comment]
To simplify the question; suppose the offer's code has access to an approximate random number generator; and decides to fail in relation to a sample thereof; suppose the return for successful cleaning is 2-to-1, ie if cleaner spends 1, and offer fails, cleaner gets 2; then this type of offer has expected return of 0 (ie is not cleanable based on self-interest).
