### ISSUE TITLE
`LiquidityProvider`'s function `computeAsk/BidProvision` is incorrect when underlying logic is `MultiUser`

### ISSUE THREAD

**Issue by jkrivine** [mangrovedao/mangrove-ts#557]
**Describe the bug**
In multi User contract, the available balance for an update might be stored in the `offerData` map as `free_wei`. Currenlty `getMissingProvision` assumes the balance is always 0 for multi user contracts.

**Comment by espendk** [comment]
It appears `getMissingProvision` has been revised - @jkrivine is this issue still relevant?

**Comment by lnist** [comment]
Fixed by https://github.com/mangrovedao/mangrove-ts/pull/1290 . As Espen mentions the code had previously been revised to take Forwarder(multi-user) contracts into account, but still did not account for provision locked in "naked offers" without contract code. That is now fixed.
