### ISSUE TITLE
[Feature] Local configuration for monorepo in _one_ place

### ISSUE THREAD

**Issue by adhusson** [mangrovedao/mangrove-ts#57]
vd says: "as a dev/trader i would also like to be able to declare my .env conveniently -in one format eg json - at one place eg in the root dir of my local copy of mangrove with all my human names for contract adresses and nodes"

Could be solved by .env files, or more advanced stuff like `config`, or a custom solution.

┆Issue is synchronized with this [Monday item](https://mangrovedao.monday.com/boards/3894180513/pulses/3902027104) by [Unito](https://www.unito.io)

**Comment by peterMangrove** [comment]
This is solved by the config setup
