### ISSUE TITLE
Reenable GH Projects Automations workflow

### ISSUE THREAD

**Issue by dontrolle** [mangrovedao/mangrove-ts#848]
**Is your feature request related to a problem? Please describe.**
We use the action https://github.com/leonsteinhaeuser/project-beta-automations in the workflow, "Project automations (organization)", essentially to open (and close) GitHub project tasks with status's reflecting PRs. Recently the author signaled that due to GitHub API changes he would not have the v1 work after October 2022. So we upgraded the Action (the Dependabot PR was green, after all).

However, the merge uncovered that the new version does require some changes to permissions (but also has better support and instructions for GitHub App). 

We're not using GH Project very actively, right now, so for now we've disabled the workflow, and logged this issue. 

This issue is only relevant if our usage of GH Projeects take up again.

**Describe the solution you'd like**
Fix our usage of the Action in question in "Project automations (organization)" and reenable the workflow.

**Describe alternatives you've considered**
Find an alternative way of having PR's and their status show up in GH Projects.

**Comment by espendk** [comment]
deprecated, we no longer use GH Projects
